version: "3"

services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    command: --dev --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --protected-mode no
    networks:
      - backend

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: timescaledb
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - backend

  chatly-server:
    image: oven/bun:latest
    container_name: chatly-server
    volumes:
      - .:/app
    working_dir: /app
    command: bun index.ts
    ports:
      - "3000:3000"
    depends_on:
      - livekit
      - timescaledb
    networks:
      - backend

volumes:
  timescaledb_data:

networks:
  backend:
