services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    command: --dev --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --protected-mode no
    networks:
      - backend

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: "timescaledb"
    environment:
      POSTGRES_PASSWORD: ${API_SECRET}
      POSTGRES_USER: chatly
      POSTGRES_DB: chatlydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatly -d chatlydb"]
      interval: 5s
      retries: 5
      timeout: 5s
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - backend

  chatly-server:
    image: oven/bun:latest
    container_name: chatly-server
    volumes:
      - .:/app
    working_dir: /app
    command: bun --watch index.ts
    ports:
      - "3000:3000"
    depends_on:
      timescaledb:
        condition: service_healthy
      livekit:
        condition: service_started
    networks:
      - backend
    develop:
      watch:
        - action: rebuild
          path: .

volumes:
  timescaledb_data:

networks:
  backend:
